### ISSUE TITLE
[Bug] multi-ticker option - load many stock prices 

### ISSUE THREAD

**Issue by msh855** [OpenBB-finance/OpenBB#5869]
In practice it is rarely the case that people will use just on stock. Instead people usually want to download the prices for all stocks in their portfolio. 

I have tried to parallelise myself the loading of historical prices, but it seems the openBB function is not well integrated with parallelize tools. At least the way I tried. 

Here an example: 

```
from joblib import Parallel, delayed
tickers = ['AAPL', 'TSLA']
func = obb.equity.price.historical
results = Parallel(n_jobs=2, prefer="threads")(delayed(func)(symbol = [tic], provider = 'yfinance') for tic in tickers)
```

This gives an error: 

`openbb_core.app.model.abstract.error.OpenBBError: 'AAPL'`

I have tried with other libraries to download yahoo prices and there was no problem in using `joblib`

**Comment by jmaslek** [comment]
Can you provide the code that worked for you with yf?

**Comment by msh855** [comment]
Sure here is it: 


```
from tqdm import tqdm
from joblib import Parallel, delayed
import yfinance as yf

tickers = ['SMT.L', 'FAS.L', 'HVPE.L', 'III.L']

def load_stock(ticker):
    msft = yf.Ticker(ticker)
    return msft.history()

results = Parallel(n_jobs=4, prefer="threads")(delayed(load_stock)(ticker=tic) for tic in tqdm(tickers))

```

**Comment by msh855** [comment]
No, that is what I did initially

**Comment by jmaslek** [comment]
So there is an issue when using yf.download vs yf.Ticker().history.   The code you provided uses .history -- can you get it to work with .download ?

**Comment by jmaslek** [comment]
Okay I think I know what the issue is.

The code you provided earlier works because it uses Ticker().history.  obb fails because it uses yfinance.download.

Looking through the source code, I think download fails because yf automatically uses threads for the .download function where history does not.  My guess is trying to parallelize this is causing the issue because the DFS dictionary is looking for a ticker in a different process.

So the solution is to pass threads=False into yf.download.  Not at my computer right now but will confirm this later. We can either patch later or there is a small chance you can use a kwargs value (don't think this is the case yet).

**Comment by jmaslek** [comment]
https://github.com/OpenBB-finance/OpenBBTerminal/pull/5872/

**Comment by deeleeramone** [comment]
> In practice it is rarely the case that people will use just on stock. Instead people usually want to download the prices for all stocks in their portfolio.
> 
> I have tried to parallelise myself the loading of historical prices, but it seems the openBB function is not well integrated with parallelize tools. At least the way I tried.
> 
> Here an example:
> 
> ```
> from joblib import Parallel, delayed
> tickers = ['AAPL', 'TSLA']
> func = obb.equity.price.historical
> results = Parallel(n_jobs=2, prefer="threads")(delayed(func)(symbol = [tic], provider = 'yfinance') for tic in tickers)
> ```
> 
> This gives an error:
> 
> `openbb_core.app.model.abstract.error.OpenBBError: 'AAPL'`
> 
> I have tried with other libraries to download yahoo prices and there was no problem in using `joblib`



This specific error was resolved here: https://github.com/OpenBB-finance/OpenBBTerminal/pull/5845
